## Extracted Data Organization

Using data from the Python Weather Info App

In [1]:
import os
import pandas as pd
import numpy as np

df = pd.read_csv("extracted_functions.csv")

df

,function_name,description,parameters
0,get_weather,# Function to fetch and display weather inform...,['city_name']
1,search_city,# Function to handle the search action when th...,[]
2,on_enter_press,# Function to bind the Enter key to the search...,['event']
3,resize_bg,# Function to handle resizing of the backgroun...,['event']
4,set_background,# Function to set the background image (path i...,['image_path']
5,show_default_info,# Function to show the default weather info fo...,[]

In [2]:
# Fix some formatting to clean it up:

# Remove the leading "# " from the description column:
df["description"] = df["description"].str.strip("# ")

# Remove the square brackets and single quotes from the parameters column:
df["parameters"] = df["parameters"].str.strip("[]'")

df = df.replace(r'^\s*$', np.nan, regex=True)

df

,function_name,description,parameters
0,get_weather,Function to fetch and display weather informat...,city_name
1,search_city,Function to handle the search action when the ...,NaN
2,on_enter_press,Function to bind the Enter key to the search f...,event
3,resize_bg,Function to handle resizing of the background ...,event
4,set_background,Function to set the background image (path is ...,image_path
5,show_default_info,Function to show the default weather info for ...,NaN

In [6]:
# Add new column with the purpose of each function:
purpose_list = ['API/data fetching', 'user interaction', 'event handling', 'UI handling', 'UI handling', 'UI handling']
df["purpose"] = purpose_list

# Add new column with the file names:
file_name_list = ['weather_app.py', 'weather_app.py', 'weather_app.py', 'weather_app.py', 'weather_app.py', 'weather_app.py']
df["file_name"] = file_name_list

df

,function_name,description,parameters,file_name,purpose
0,get_weather,Function to fetch and display weather informat...,city_name,weather_app.py,API/data fetching
1,search_city,Function to handle the search action when the ...,NaN,weather_app.py,user interaction
2,on_enter_press,Function to bind the Enter key to the search f...,event,weather_app.py,event handling
3,resize_bg,Function to handle resizing of the background ...,event,weather_app.py,UI handling
4,set_background,Function to set the background image (path is ...,image_path,weather_app.py,UI handling
5,show_default_info,Function to show the default weather info for ...,NaN,weather_app.py,UI handling

In [9]:

df.to_json('weather_app_functions.json', orient='records', indent=4)