## SQL Notebook to view codebase extraction data

In [2]:
import pandas as pd
import sqlite3

In [14]:
df = pd.read_json('weather_app_functions.json')
df

,function_name,description,parameters,file_name,purpose
0,get_weather,Function to fetch and display weather informat...,city_name,weather_app.py,API/data fetching
1,search_city,Function to handle the search action when the ...,NaN,weather_app.py,user interaction
2,on_enter_press,Function to bind the Enter key to the search f...,event,weather_app.py,event handling
3,resize_bg,Function to handle resizing of the background ...,event,weather_app.py,UI handling
4,set_background,Function to set the background image (path is ...,image_path,weather_app.py,UI handling
5,show_default_info,Function to show the default weather info for ...,NaN,weather_app.py,UI handling

In [18]:
conn = sqlite3.connect("codebase_knowledge.db") # This connects Python to your database file
df.to_sql("functions", conn, if_exists="replace", index=False) # This writes the DataFrame to a table named "functions" in the database, replacing it if it already exists and not including the DataFrame index as a column.

6

### SQL Queries:

In [19]:
pd.read_sql_query("SELECT * FROM functions;", conn)

,function_name,description,parameters,file_name,purpose
0,get_weather,Function to fetch and display weather informat...,city_name,weather_app.py,API/data fetching
1,search_city,Function to handle the search action when the ...,NaN,weather_app.py,user interaction
2,on_enter_press,Function to bind the Enter key to the search f...,event,weather_app.py,event handling
3,resize_bg,Function to handle resizing of the background ...,event,weather_app.py,UI handling
4,set_background,Function to set the background image (path is ...,image_path,weather_app.py,UI handling
5,show_default_info,Function to show the default weather info for ...,NaN,weather_app.py,UI handling

In [25]:
pd.read_sql_query("SELECT function_name from functions WHERE purpose = 'UI handling';", conn)

       function_name
0          resize_bg
1     set_background
2  show_default_info

In [28]:
pd.read_sql_query("SELECT purpose, COUNT(*) FROM functions GROUP BY purpose;", conn)

             purpose  COUNT(*)
0  API/data fetching         1
1        UI handling         3
2     event handling         1
3   user interaction         1